# Generated by Django 3.2.5 on 2021-07-12 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('employee_id', models.CharField(db_index=True, max_length=12)),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Last updated')),
            ],
        ),
    ]
