# Generated by Django 3.2.5 on 2021-07-16 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0002_alter_employee_hourly_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('leader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employment.employee')),
            ],
        ),
        migrations.CreateModel(
            name='TeamEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Last updated')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employment.employee')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employment.team')),
            ],
        ),
    ]
