# Generated by Django 3.2.5 on 2021-07-17 19:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0005_alter_team_leader'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='teams',
            field=models.ManyToManyField(through='employment.TeamEmployee', to='employment.Team'),
        ),
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(through='employment.TeamEmployee', to='employment.Employee'),
        ),
        migrations.AlterField(
            model_name='team',
            name='leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team_leader_employee', to='employment.employee'),
        ),
        migrations.CreateModel(
            name='WorkArrangement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'Fulltime'), (2, 'Parttime')])),
                ('percentage', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)])),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employment.employee')),
            ],
        ),
    ]
