# Generated by Django 3.2.5 on 2021-07-17 19:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0006_auto_20210717_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='workarrangement',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workarrangement',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Last updated'),
        ),
    ]
